/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * JSON Placeholder API
 * See https://jsonplaceholder.typicode.com/
 * OpenAPI spec version: 1.0.0
 */

export interface Post {
  id: number;
  userId: number;
  title: string;
  body: string;
}
