/**
 * Generated by orval v6.11.1 🍺
 * Do not edit manually.
 * JSON Placeholder API
 * See https://jsonplaceholder.typicode.com/
 * OpenAPI spec version: 1.0.0
 */
import type { Post } from './post';

export type PostList = Post[];
